development:
  adapter: postgresql
  database: music_app_development
  pool: 25

test:
  adapter: postgresql
  database: music_app_test
  pool: 5

production:
  adapter: postgresql
  database: music_app_production
