development:
  adapter: postgresql
  database: ocarina_development
  pool: 25

test:
  adapter: postgresql
  database: ocarina_test
  pool: 5

production:
  adapter: postgresql
  database: ocarina_production
