#= require jquery
#= require bootstrap
#= require soundcloud
#= require angular
#= require angular-resource
#= require angular-sanitize
#= require angular-bootstrap-prettify
#= require ui-bootstrap
#= require lodash
#= require ocarina
#= require_tree ./controllers/
#= require services
#= require directives
#= require filters
#= require_self
