#= require jquery
#= require angular
#= require angular-resource
#= require angular-sanitize
#= require angular-bootstrap-prettify
#= require ui-bootstrap
#= require underscore
#= require ocarina
#= require_tree ./controllers/
#= require services
#= require directives
#= require filters
#= require audio5
#= require_self
